--------------------------------------------------------
--  File created - Thursday-August-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS_IN_APP
--------------------------------------------------------

  CREATE TABLE "EDIK_TEST_GOOD"."ORDERS_IN_APP" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 0 MAXVALUE 99999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDERER_NAME" VARCHAR2(50 BYTE), 
	"ORDERER_ADDRESS" VARCHAR2(50 BYTE), 
	"SUMM" NUMBER, 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "EDIK_TEST_GOOD"."ORDERS_IN_APP"."ID" IS 'ID- заказа ';
   COMMENT ON COLUMN "EDIK_TEST_GOOD"."ORDERS_IN_APP"."ORDERER_NAME" IS 'Имя заказчика';
   COMMENT ON COLUMN "EDIK_TEST_GOOD"."ORDERS_IN_APP"."ORDERER_ADDRESS" IS 'Адресс заказчика';
   COMMENT ON COLUMN "EDIK_TEST_GOOD"."ORDERS_IN_APP"."SUMM" IS 'Сумма заказа';
   COMMENT ON COLUMN "EDIK_TEST_GOOD"."ORDERS_IN_APP"."ORDER_DATE" IS 'Текущее время, когда заказ был выполнен
';
--------------------------------------------------------
--  DDL for Table DETAILS_ORDER
--------------------------------------------------------

  CREATE TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" 
   (	"POSITION_NUMBER" NUMBER, 
	"PRODUCT_SERIAL_NUMBER" VARCHAR2(100 BYTE), 
	"PRODUCT_QUANTITY" NUMBER, 
	"ID_ORDER" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "EDIK_TEST_GOOD"."DETAILS_ORDER"."POSITION_NUMBER" IS 'Номер позиции';
   COMMENT ON COLUMN "EDIK_TEST_GOOD"."DETAILS_ORDER"."PRODUCT_SERIAL_NUMBER" IS 'Серийный номер товара';
   COMMENT ON COLUMN "EDIK_TEST_GOOD"."DETAILS_ORDER"."PRODUCT_QUANTITY" IS 'Колличество продукта';
   COMMENT ON COLUMN "EDIK_TEST_GOOD"."DETAILS_ORDER"."ID_ORDER" IS 'ID-шник из первой таблицы';
   COMMENT ON COLUMN "EDIK_TEST_GOOD"."DETAILS_ORDER"."PRODUCT_NAME" IS 'Название товара';
--------------------------------------------------------
--  DDL for Index ORDERS_IN_APP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDIK_TEST_GOOD"."ORDERS_IN_APP_PK" ON "EDIK_TEST_GOOD"."ORDERS_IN_APP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETAILS_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDIK_TEST_GOOD"."DETAILS_ORDER_PK" ON "EDIK_TEST_GOOD"."DETAILS_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ORDERS_IN_APP
--------------------------------------------------------

  ALTER TABLE "EDIK_TEST_GOOD"."ORDERS_IN_APP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."ORDERS_IN_APP" MODIFY ("ORDERER_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."ORDERS_IN_APP" MODIFY ("ORDERER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."ORDERS_IN_APP" MODIFY ("SUMM" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."ORDERS_IN_APP" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."ORDERS_IN_APP" ADD CONSTRAINT "ORDERS_IN_APP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETAILS_ORDER
--------------------------------------------------------

  ALTER TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" MODIFY ("POSITION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" MODIFY ("PRODUCT_SERIAL_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" MODIFY ("PRODUCT_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" MODIFY ("ID_ORDER" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" ADD CONSTRAINT "DETAILS_ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DETAILS_ORDER
--------------------------------------------------------

  ALTER TABLE "EDIK_TEST_GOOD"."DETAILS_ORDER" ADD CONSTRAINT "FK_DETAILS_ORDER_TO_ORDERS_IN_APP" FOREIGN KEY ("ID_ORDER")
	  REFERENCES "EDIK_TEST_GOOD"."ORDERS_IN_APP" ("ID") ENABLE;
